version: '3.8'

services:
  # The app service
  app:
    image: testgeek1592021/todo-app:v1
    container_name: todo-app-pro
    ports:
      - "80:3000" # Mapping GCP port 80 to container port 3000
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@local-postgres:5432/todo_db?schema=public
    depends_on:
      - db  # wait for the database service to be ready 
      

  # The databse service
  db:
    image: postgres:16-alpine
    container_name: todo-db-pro
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: todo_db
    volumes:
      - db_data:/var/lib/postgresql/data

# This saves the database data even if the container is removed
volumes:
  db_data: